# Generated by Django 4.1.3 on 2022-12-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('client', models.CharField(max_length=1000, verbose_name='Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.person')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specjalizacja')),
            ],
            bases=('bookapp.person',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('description', models.CharField(max_length=1000, verbose_name='Opis')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Przepracowany czas')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.person', verbose_name='Wykonawca')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapp.project', verbose_name='Projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.person')),
                ('dev_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.supervisor', verbose_name='Przełożony')),
            ],
            bases=('bookapp.person',),
        ),
    ]
