# Generated by Django 4.1.3 on 2022-12-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_project_supervisor_task_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(default=1, upload_to='', verbose_name='plik'),
            preserve_default=False,
        ),
    ]
