# Generated by Django 4.1.3 on 2022-12-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
    ]
