# Generated by Django 4.1.3 on 2022-12-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.CharField(default=1, max_length=10, verbose_name='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Plik'),
        ),
    ]
