# Generated by Django 4.1.3 on 2022-12-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_project_test_alter_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test',
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Plik'),
        ),
    ]
