# Generated by Django 4.1.3 on 2022-12-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_remove_project_test_alter_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=500, verbose_name='Imię i nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('image', models.ImageField(upload_to='pics', verbose_name='Wykres')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.author', verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Epoka literacka')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Plik')),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='book',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.period', verbose_name='Epoka literacka'),
        ),
    ]
