# Generated by Django 4.1.3 on 2023-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookapp",
            "0009_author_book_period_text_remove_supervisor_person_ptr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.CharField(default=1, max_length=50, verbose_name="Imię"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="period",
            name="beginning",
            field=models.IntegerField(default=1, verbose_name="Rok rozpoczęcia"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="period",
            name="description",
            field=models.CharField(default=1, max_length=1000, verbose_name="Opis"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="period",
            name="end",
            field=models.IntegerField(default=1, verbose_name="Rok zakończenia"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="surname",
            field=models.CharField(max_length=50, verbose_name="Nazwisko"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                upload_to="bookapp/static/bookapp/", verbose_name="Wykres"
            ),
        ),
    ]
