# Generated by Django 4.1.3 on 2023-01-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0010_author_name_period_beginning_period_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bookapp.author",
                verbose_name="Autor",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                upload_to="bookapp/static/bookapp/", verbose_name="Wykres"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bookapp.period",
                verbose_name="Epoka literacka",
            ),
        ),
    ]
